/**
 * @fileoverview Curated meals database — 24 meals (8 breakfast, 8 lunch, 8 dinner).
 * Each ingredient includes per-serving cost and allergen info for safe filtering.
 *
 * Dietary tags:
 *  - "vegan"        — no animal products
 *  - "vegetarian"   — no meat/fish (may have dairy/eggs)
 *  - "keto"         — low-carb, high-fat
 *  - "omnivore"     — contains meat or fish
 *
 * Allergen codes: "gluten" | "dairy" | "eggs" | "nuts" | "shellfish" | "soy"
 */

/* global MEALS_DATA */
const MEALS_DATA = {
  meals: [

    /* ========================================================
       BREAKFAST MEALS
       ======================================================== */

    {
      id: 'bf-001',
      name: 'Avocado Toast with Poached Eggs',
      type: 'breakfast',
      tags: ['vegetarian'],
      cuisine: 'american',
      servings: 1,
      prepTime: 5,
      cookTime: 10,
      difficulty: 'easy',
      emoji: '🥑',
      description: 'Creamy mashed avocado on golden sourdough topped with silky poached eggs',
      costPerServing: 3.08,
      ingredients: [
        { name: 'Sourdough bread',   quantity: 2,    unit: 'slices', cost: 0.80, category: 'Bakery',       allergens: ['gluten'] },
        { name: 'Avocado',           quantity: 1,    unit: 'whole',  cost: 1.50, category: 'Produce',      allergens: [] },
        { name: 'Eggs',              quantity: 2,    unit: 'whole',  cost: 0.60, category: 'Dairy & Eggs', allergens: ['eggs'] },
        { name: 'Lemon',             quantity: 0.5,  unit: 'whole',  cost: 0.15, category: 'Produce',      allergens: [] },
        { name: 'Olive oil',         quantity: 1,    unit: 'tsp',    cost: 0.10, category: 'Pantry',       allergens: [] },
        { name: 'Red pepper flakes', quantity: 0.25, unit: 'tsp',    cost: 0.02, category: 'Pantry',       allergens: [] },
        { name: 'Salt',              quantity: 1,    unit: 'pinch',  cost: 0.01, category: 'Pantry',       allergens: [] },
      ],
      steps: [
        'Toast sourdough slices until golden and crispy',
        'Mash avocado with lemon juice, salt, and a pinch of pepper',
        'Bring a pot of water to a gentle simmer; add a splash of vinegar',
        'Crack eggs into the simmering water and poach for 3–4 minutes',
        'Spread avocado onto toast and top with poached eggs',
        'Finish with red pepper flakes and a drizzle of olive oil',
      ],
    },

    {
      id: 'bf-002',
      name: 'Mixed Berry Smoothie Bowl',
      type: 'breakfast',
      tags: ['vegan', 'vegetarian'],
      cuisine: 'american',
      servings: 1,
      prepTime: 8,
      cookTime: 0,
      difficulty: 'easy',
      emoji: '🫐',
      description: 'Thick blended berry base topped with granola, seeds, and fresh fruit',
      costPerServing: 4.20,
      ingredients: [
        { name: 'Frozen mixed berries', quantity: 1,    unit: 'cup',  cost: 1.50, category: 'Frozen',   allergens: [] },
        { name: 'Frozen banana',        quantity: 1,    unit: 'whole', cost: 0.30, category: 'Frozen',   allergens: [] },
        { name: 'Almond milk',          quantity: 0.5,  unit: 'cup',  cost: 0.30, category: 'Dairy-Free', allergens: ['nuts'] },
        { name: 'Granola',             quantity: 0.25, unit: 'cup',  cost: 0.60, category: 'Pantry',    allergens: ['gluten', 'nuts'] },
        { name: 'Chia seeds',          quantity: 1,    unit: 'tbsp', cost: 0.20, category: 'Pantry',    allergens: [] },
        { name: 'Fresh strawberries',  quantity: 5,    unit: 'whole', cost: 0.80, category: 'Produce',  allergens: [] },
        { name: 'Honey',               quantity: 1,    unit: 'tsp',  cost: 0.10, category: 'Pantry',    allergens: [] },
        { name: 'Coconut flakes',      quantity: 1,    unit: 'tbsp', cost: 0.20, category: 'Pantry',    allergens: [] },
      ],
      steps: [
        'Add frozen berries, banana, and almond milk to a blender',
        'Blend until thick and smooth — add more milk if needed',
        'Pour into a bowl; it should be spoonable, not drinkable',
        'Top with granola in a row across the centre',
        'Add fresh strawberries, chia seeds, and coconut flakes',
        'Drizzle with honey and serve immediately',
      ],
    },

    {
      id: 'bf-003',
      name: 'Warm Oatmeal with Caramelised Banana',
      type: 'breakfast',
      tags: ['vegan', 'vegetarian'],
      cuisine: 'american',
      servings: 1,
      prepTime: 2,
      cookTime: 8,
      difficulty: 'easy',
      emoji: '🥣',
      description: 'Creamy rolled oats topped with pan-caramelised banana and cinnamon',
      costPerServing: 1.55,
      ingredients: [
        { name: 'Rolled oats',    quantity: 0.5, unit: 'cup',  cost: 0.30, category: 'Pantry',    allergens: ['gluten'] },
        { name: 'Oat milk',       quantity: 1,   unit: 'cup',  cost: 0.40, category: 'Dairy-Free', allergens: [] },
        { name: 'Banana',         quantity: 1,   unit: 'whole', cost: 0.30, category: 'Produce',  allergens: [] },
        { name: 'Maple syrup',    quantity: 1,   unit: 'tbsp', cost: 0.20, category: 'Pantry',    allergens: [] },
        { name: 'Cinnamon',       quantity: 0.5, unit: 'tsp',  cost: 0.05, category: 'Pantry',    allergens: [] },
        { name: 'Salt',           quantity: 1,   unit: 'pinch', cost: 0.01, category: 'Pantry',   allergens: [] },
        { name: 'Coconut oil',    quantity: 0.5, unit: 'tsp',  cost: 0.10, category: 'Pantry',    allergens: [] },
        { name: 'Walnuts',        quantity: 1,   unit: 'tbsp', cost: 0.30, category: 'Pantry',    allergens: ['nuts'] },
      ],
      steps: [
        'Bring oat milk to a simmer in a small saucepan',
        'Stir in rolled oats and a pinch of salt',
        'Cook on medium-low, stirring often, for 5–6 minutes',
        'Slice banana lengthways and pan-fry in coconut oil 1–2 min per side',
        'Pour oatmeal into a bowl and top with caramelised banana',
        'Drizzle with maple syrup, sprinkle cinnamon and crushed walnuts',
      ],
    },

    {
      id: 'bf-004',
      name: 'Keto Egg & Cheese Muffins',
      type: 'breakfast',
      tags: ['keto'],
      cuisine: 'american',
      servings: 1,
      prepTime: 5,
      cookTime: 20,
      difficulty: 'easy',
      emoji: '🧁',
      description: 'Fluffy baked egg muffins with cheddar, spinach, and crispy bacon — zero carbs',
      costPerServing: 2.85,
      ingredients: [
        { name: 'Eggs',            quantity: 3,   unit: 'whole',  cost: 0.90, category: 'Dairy & Eggs', allergens: ['eggs'] },
        { name: 'Cheddar cheese',  quantity: 0.5, unit: 'cup',   cost: 0.80, category: 'Dairy & Eggs', allergens: ['dairy'] },
        { name: 'Baby spinach',    quantity: 0.5, unit: 'cup',   cost: 0.30, category: 'Produce',      allergens: [] },
        { name: 'Bacon',           quantity: 2,   unit: 'slices', cost: 0.60, category: 'Proteins',    allergens: [] },
        { name: 'Heavy cream',     quantity: 2,   unit: 'tbsp',  cost: 0.20, category: 'Dairy & Eggs', allergens: ['dairy'] },
        { name: 'Garlic powder',   quantity: 0.25, unit: 'tsp', cost: 0.03, category: 'Pantry',        allergens: [] },
        { name: 'Salt',            quantity: 1,   unit: 'pinch', cost: 0.01, category: 'Pantry',       allergens: [] },
        { name: 'Black pepper',    quantity: 1,   unit: 'pinch', cost: 0.01, category: 'Pantry',       allergens: [] },
      ],
      steps: [
        'Preheat oven to 180 °C / 350 °F and grease a muffin tin',
        'Cook bacon in a pan until crisp; chop into small pieces',
        'Whisk eggs with heavy cream, garlic powder, salt, and pepper',
        'Divide spinach and bacon into muffin cups',
        'Pour egg mixture over, filling each cup ¾ full',
        'Top with shredded cheddar cheese',
        'Bake 18–20 minutes until puffed and golden — serve warm',
      ],
    },

    {
      id: 'bf-005',
      name: 'Greek Yogurt Parfait',
      type: 'breakfast',
      tags: ['vegetarian'],
      cuisine: 'american',
      servings: 1,
      prepTime: 5,
      cookTime: 0,
      difficulty: 'easy',
      emoji: '🍦',
      description: 'Layers of creamy Greek yogurt, honey granola, and vibrant seasonal fruit',
      costPerServing: 3.50,
      ingredients: [
        { name: 'Greek yogurt',      quantity: 1,    unit: 'cup',  cost: 1.20, category: 'Dairy & Eggs', allergens: ['dairy'] },
        { name: 'Granola',           quantity: 0.25, unit: 'cup',  cost: 0.60, category: 'Pantry',       allergens: ['gluten', 'nuts'] },
        { name: 'Blueberries',       quantity: 0.5,  unit: 'cup',  cost: 0.90, category: 'Produce',      allergens: [] },
        { name: 'Raspberries',       quantity: 0.25, unit: 'cup',  cost: 0.60, category: 'Produce',      allergens: [] },
        { name: 'Honey',             quantity: 1,    unit: 'tbsp', cost: 0.15, category: 'Pantry',       allergens: [] },
        { name: 'Vanilla extract',   quantity: 0.25, unit: 'tsp',  cost: 0.05, category: 'Pantry',       allergens: [] },
      ],
      steps: [
        'Stir vanilla extract into Greek yogurt until combined',
        'Spoon half the yogurt into a tall glass or bowl',
        'Add a layer of granola, then blueberries and raspberries',
        'Top with remaining yogurt and repeat the layers',
        'Drizzle with honey and serve immediately',
      ],
    },

    {
      id: 'bf-006',
      name: 'Spiced Masala Omelette',
      type: 'breakfast',
      tags: ['vegetarian'],
      cuisine: 'indian',
      servings: 1,
      prepTime: 5,
      cookTime: 8,
      difficulty: 'easy',
      emoji: '🍳',
      description: 'Fluffy egg omelette loaded with onion, tomato, green chilli, and aromatic spices',
      costPerServing: 2.20,
      ingredients: [
        { name: 'Eggs',              quantity: 3,   unit: 'whole',  cost: 0.90, category: 'Dairy & Eggs', allergens: ['eggs'] },
        { name: 'Onion',             quantity: 0.5, unit: 'whole',  cost: 0.20, category: 'Produce',      allergens: [] },
        { name: 'Tomato',            quantity: 1,   unit: 'whole',  cost: 0.30, category: 'Produce',      allergens: [] },
        { name: 'Green chilli',      quantity: 1,   unit: 'whole',  cost: 0.10, category: 'Produce',      allergens: [] },
        { name: 'Fresh coriander',   quantity: 2,   unit: 'tbsp',   cost: 0.15, category: 'Produce',      allergens: [] },
        { name: 'Turmeric powder',   quantity: 0.25, unit: 'tsp',   cost: 0.03, category: 'Pantry',       allergens: [] },
        { name: 'Cumin seeds',       quantity: 0.25, unit: 'tsp',   cost: 0.03, category: 'Pantry',       allergens: [] },
        { name: 'Butter',            quantity: 1,   unit: 'tsp',    cost: 0.10, category: 'Dairy & Eggs', allergens: ['dairy'] },
        { name: 'Salt',              quantity: 1,   unit: 'pinch',  cost: 0.01, category: 'Pantry',       allergens: [] },
      ],
      steps: [
        'Finely dice onion, tomato, and green chilli',
        'Whisk eggs with turmeric, salt, and chopped coriander',
        'Heat butter in a non-stick pan over medium heat',
        'Sauté cumin seeds until they sizzle, then add onion',
        'Cook onion 2 minutes; add tomato and chilli, cook 1 minute',
        'Pour egg mixture over the filling and cook until set',
        'Fold and serve hot with toast or flatbread',
      ],
    },

    {
      id: 'bf-007',
      name: 'Fluffy Buttermilk Pancakes',
      type: 'breakfast',
      tags: ['vegetarian'],
      cuisine: 'american',
      servings: 1,
      prepTime: 5,
      cookTime: 15,
      difficulty: 'easy',
      emoji: '🥞',
      description: 'Light, airy pancakes served with maple syrup and fresh berries',
      costPerServing: 1.80,
      ingredients: [
        { name: 'All-purpose flour', quantity: 0.75, unit: 'cup',  cost: 0.20, category: 'Pantry',       allergens: ['gluten'] },
        { name: 'Buttermilk',        quantity: 0.75, unit: 'cup',  cost: 0.30, category: 'Dairy & Eggs', allergens: ['dairy'] },
        { name: 'Egg',               quantity: 1,   unit: 'whole', cost: 0.30, category: 'Dairy & Eggs', allergens: ['eggs'] },
        { name: 'Butter',            quantity: 1,   unit: 'tbsp', cost: 0.20, category: 'Dairy & Eggs', allergens: ['dairy'] },
        { name: 'Baking powder',     quantity: 1,   unit: 'tsp',  cost: 0.02, category: 'Pantry',       allergens: [] },
        { name: 'Sugar',             quantity: 1,   unit: 'tbsp', cost: 0.05, category: 'Pantry',       allergens: [] },
        { name: 'Salt',              quantity: 1,   unit: 'pinch', cost: 0.01, category: 'Pantry',      allergens: [] },
        { name: 'Maple syrup',       quantity: 2,   unit: 'tbsp', cost: 0.40, category: 'Pantry',       allergens: [] },
        { name: 'Mixed berries',     quantity: 0.25, unit: 'cup', cost: 0.40, category: 'Produce',      allergens: [] },
      ],
      steps: [
        'Whisk flour, baking powder, sugar, and salt in a bowl',
        'In a separate bowl, mix buttermilk, egg, and melted butter',
        'Combine wet and dry ingredients — do not overmix (lumps are fine)',
        'Heat a lightly greased pan over medium heat',
        'Pour ¼ cup batter per pancake; cook until bubbles form on top (~2 min)',
        'Flip and cook 1 more minute until golden',
        'Serve stacked with maple syrup and fresh berries',
      ],
    },

    {
      id: 'bf-008',
      name: 'Scrambled Tofu Breakfast Toast',
      type: 'breakfast',
      tags: ['vegan', 'vegetarian'],
      cuisine: 'american',
      servings: 1,
      prepTime: 5,
      cookTime: 10,
      difficulty: 'easy',
      emoji: '🧇',
      description: 'Tumeric-spiced scrambled tofu on multigrain toast — a protein-packed vegan classic',
      costPerServing: 3.00,
      ingredients: [
        { name: 'Firm tofu',        quantity: 150,  unit: 'g',     cost: 1.00, category: 'Proteins',  allergens: ['soy'] },
        { name: 'Multigrain bread', quantity: 2,    unit: 'slices', cost: 0.60, category: 'Bakery',   allergens: ['gluten'] },
        { name: 'Olive oil',        quantity: 1,    unit: 'tbsp',  cost: 0.15, category: 'Pantry',    allergens: [] },
        { name: 'Turmeric',         quantity: 0.5,  unit: 'tsp',   cost: 0.05, category: 'Pantry',   allergens: [] },
        { name: 'Nutritional yeast',quantity: 1,    unit: 'tbsp',  cost: 0.20, category: 'Pantry',   allergens: [] },
        { name: 'Garlic powder',    quantity: 0.25, unit: 'tsp',   cost: 0.03, category: 'Pantry',   allergens: [] },
        { name: 'Baby spinach',     quantity: 0.5,  unit: 'cup',   cost: 0.30, category: 'Produce',  allergens: [] },
        { name: 'Cherry tomatoes',  quantity: 6,    unit: 'whole', cost: 0.50, category: 'Produce',  allergens: [] },
        { name: 'Salt',             quantity: 1,    unit: 'pinch', cost: 0.01, category: 'Pantry',   allergens: [] },
      ],
      steps: [
        'Press tofu in a paper towel to remove excess moisture',
        'Crumble tofu into rough chunks in a bowl',
        'Heat olive oil in a pan over medium-high heat',
        'Add crumbled tofu and cook, stirring, for 3 minutes',
        'Add turmeric, nutritional yeast, garlic powder, and salt',
        'Stir in baby spinach until wilted (about 1 minute)',
        'Toast bread and halve the cherry tomatoes',
        'Pile scrambled tofu on toast and top with tomatoes',
      ],
    },

    /* ========================================================
       LUNCH MEALS
       ======================================================== */

    {
      id: 'lu-001',
      name: 'Grilled Chicken Caesar Salad',
      type: 'lunch',
      tags: ['omnivore'],
      cuisine: 'american',
      servings: 1,
      prepTime: 10,
      cookTime: 12,
      difficulty: 'medium',
      emoji: '🥗',
      description: 'Crisp romaine, house-made Caesar dressing, grilled chicken, and crunchy croutons',
      costPerServing: 5.50,
      ingredients: [
        { name: 'Chicken breast',  quantity: 150, unit: 'g',     cost: 2.00, category: 'Proteins',    allergens: [] },
        { name: 'Romaine lettuce', quantity: 2,   unit: 'cups',  cost: 0.80, category: 'Produce',     allergens: [] },
        { name: 'Parmesan',        quantity: 2,   unit: 'tbsp',  cost: 0.50, category: 'Dairy & Eggs', allergens: ['dairy'] },
        { name: 'Croutons',        quantity: 0.25, unit: 'cup',  cost: 0.30, category: 'Bakery',      allergens: ['gluten'] },
        { name: 'Caesar dressing', quantity: 2,   unit: 'tbsp',  cost: 0.50, category: 'Pantry',      allergens: ['eggs', 'dairy'] },
        { name: 'Lemon',           quantity: 0.5, unit: 'whole', cost: 0.15, category: 'Produce',     allergens: [] },
        { name: 'Olive oil',       quantity: 1,   unit: 'tbsp',  cost: 0.15, category: 'Pantry',     allergens: [] },
        { name: 'Garlic powder',   quantity: 0.5, unit: 'tsp',   cost: 0.03, category: 'Pantry',     allergens: [] },
        { name: 'Salt',            quantity: 1,   unit: 'pinch', cost: 0.01, category: 'Pantry',     allergens: [] },
      ],
      steps: [
        'Season chicken with olive oil, garlic powder, salt, and lemon juice',
        'Grill chicken on a hot pan 5–6 minutes per side until cooked through',
        'Rest chicken 3 minutes, then slice into strips',
        'Chop romaine into bite-size pieces and place in a large bowl',
        'Add Caesar dressing and toss well to coat',
        'Top with grilled chicken, croutons, and shaved Parmesan',
        'Finish with a squeeze of fresh lemon juice',
      ],
    },

    {
      id: 'lu-002',
      name: 'Rainbow Buddha Bowl',
      type: 'lunch',
      tags: ['vegan', 'vegetarian'],
      cuisine: 'american',
      servings: 1,
      prepTime: 10,
      cookTime: 20,
      difficulty: 'medium',
      emoji: '🌈',
      description: 'Nourishing bowl of quinoa, roasted veggies, chickpeas, and tahini dressing',
      costPerServing: 4.00,
      ingredients: [
        { name: 'Quinoa',          quantity: 0.5, unit: 'cup',  cost: 0.70, category: 'Pantry',   allergens: [] },
        { name: 'Chickpeas',       quantity: 0.5, unit: 'cup',  cost: 0.40, category: 'Pantry',   allergens: [] },
        { name: 'Sweet potato',    quantity: 0.5, unit: 'whole', cost: 0.40, category: 'Produce', allergens: [] },
        { name: 'Red cabbage',     quantity: 0.25, unit: 'cup', cost: 0.20, category: 'Produce',  allergens: [] },
        { name: 'Cucumber',        quantity: 0.5, unit: 'whole', cost: 0.25, category: 'Produce', allergens: [] },
        { name: 'Avocado',         quantity: 0.5, unit: 'whole', cost: 0.75, category: 'Produce', allergens: [] },
        { name: 'Tahini',          quantity: 1,   unit: 'tbsp', cost: 0.30, category: 'Pantry',   allergens: ['nuts'] },
        { name: 'Lemon',           quantity: 0.5, unit: 'whole', cost: 0.15, category: 'Produce', allergens: [] },
        { name: 'Olive oil',       quantity: 1,   unit: 'tbsp', cost: 0.15, category: 'Pantry',   allergens: [] },
        { name: 'Paprika',         quantity: 0.5, unit: 'tsp',  cost: 0.03, category: 'Pantry',   allergens: [] },
      ],
      steps: [
        'Rinse and cook quinoa in water (2:1 ratio) for 15 minutes',
        'Peel and cube sweet potato; toss with olive oil and paprika',
        'Roast sweet potato and chickpeas at 200 °C / 400 °F for 20 minutes',
        'Shred red cabbage and slice cucumber and avocado',
        'Whisk tahini with lemon juice and 2 tbsp water for the dressing',
        'Assemble bowl: quinoa base, then arrange all toppings',
        'Drizzle with tahini dressing and serve',
      ],
    },

    {
      id: 'lu-003',
      name: 'Caprese Panini',
      type: 'lunch',
      tags: ['vegetarian'],
      cuisine: 'italian',
      servings: 1,
      prepTime: 5,
      cookTime: 5,
      difficulty: 'easy',
      emoji: '🥪',
      description: 'Pressed panini with fresh mozzarella, vine tomatoes, basil, and pesto',
      costPerServing: 4.20,
      ingredients: [
        { name: 'Ciabatta roll',      quantity: 1,   unit: 'whole', cost: 0.90, category: 'Bakery',       allergens: ['gluten'] },
        { name: 'Fresh mozzarella',   quantity: 80,  unit: 'g',     cost: 1.20, category: 'Dairy & Eggs', allergens: ['dairy'] },
        { name: 'Vine tomatoes',      quantity: 2,   unit: 'whole', cost: 0.60, category: 'Produce',      allergens: [] },
        { name: 'Fresh basil',        quantity: 5,   unit: 'leaves', cost: 0.20, category: 'Produce',     allergens: [] },
        { name: 'Pesto',              quantity: 1,   unit: 'tbsp',  cost: 0.50, category: 'Pantry',       allergens: ['nuts', 'dairy'] },
        { name: 'Balsamic glaze',     quantity: 1,   unit: 'tsp',   cost: 0.15, category: 'Pantry',       allergens: [] },
        { name: 'Olive oil',          quantity: 1,   unit: 'tsp',   cost: 0.10, category: 'Pantry',       allergens: [] },
        { name: 'Black pepper',       quantity: 1,   unit: 'pinch', cost: 0.01, category: 'Pantry',       allergens: [] },
      ],
      steps: [
        'Slice ciabatta roll in half and spread pesto on both sides',
        'Slice mozzarella and tomatoes into ½ cm rounds',
        'Layer mozzarella, tomatoes, and fresh basil inside the roll',
        'Brush the outside of the bread lightly with olive oil',
        'Press in a panini press or griddle pan for 3–4 minutes until golden',
        'Drizzle with balsamic glaze and season with black pepper',
      ],
    },

    {
      id: 'lu-004',
      name: 'Spiced Red Lentil Soup',
      type: 'lunch',
      tags: ['vegan', 'vegetarian'],
      cuisine: 'indian',
      servings: 1,
      prepTime: 5,
      cookTime: 25,
      difficulty: 'easy',
      emoji: '🍵',
      description: 'Warming red lentil soup with cumin, coriander, and a swirl of coconut milk',
      costPerServing: 2.50,
      ingredients: [
        { name: 'Red lentils',     quantity: 0.5, unit: 'cup',  cost: 0.40, category: 'Pantry',   allergens: [] },
        { name: 'Onion',           quantity: 0.5, unit: 'whole', cost: 0.20, category: 'Produce', allergens: [] },
        { name: 'Garlic',          quantity: 2,   unit: 'cloves', cost: 0.10, category: 'Produce', allergens: [] },
        { name: 'Ginger',          quantity: 1,   unit: 'tsp',  cost: 0.10, category: 'Produce',  allergens: [] },
        { name: 'Coconut milk',    quantity: 0.25, unit: 'cup', cost: 0.40, category: 'Dairy-Free', allergens: [] },
        { name: 'Vegetable broth', quantity: 1.5, unit: 'cups', cost: 0.30, category: 'Pantry',   allergens: [] },
        { name: 'Cumin seeds',     quantity: 0.5, unit: 'tsp',  cost: 0.05, category: 'Pantry',   allergens: [] },
        { name: 'Coriander powder',quantity: 0.5, unit: 'tsp',  cost: 0.05, category: 'Pantry',   allergens: [] },
        { name: 'Turmeric',        quantity: 0.25, unit: 'tsp', cost: 0.03, category: 'Pantry',   allergens: [] },
        { name: 'Olive oil',       quantity: 1,   unit: 'tbsp', cost: 0.15, category: 'Pantry',   allergens: [] },
        { name: 'Salt',            quantity: 1,   unit: 'pinch', cost: 0.01, category: 'Pantry',  allergens: [] },
      ],
      steps: [
        'Dice onion, mince garlic, and grate ginger',
        'Heat oil in a pot; fry cumin seeds until fragrant (30 sec)',
        'Add onion and cook until golden, about 5 minutes',
        'Stir in garlic, ginger, coriander, and turmeric; cook 1 minute',
        'Add rinsed lentils and vegetable broth; bring to a boil',
        'Simmer 20 minutes until lentils are soft and soup thickens',
        'Stir in coconut milk, season with salt, and serve hot',
      ],
    },

    {
      id: 'lu-005',
      name: 'Keto Chicken Lettuce Wraps',
      type: 'lunch',
      tags: ['keto'],
      cuisine: 'asian',
      servings: 1,
      prepTime: 10,
      cookTime: 10,
      difficulty: 'easy',
      emoji: '🥬',
      description: 'Crisp butter lettuce cups filled with savory minced chicken, water chestnuts, and sesame',
      costPerServing: 5.00,
      ingredients: [
        { name: 'Minced chicken',    quantity: 150, unit: 'g',     cost: 2.00, category: 'Proteins',    allergens: [] },
        { name: 'Butter lettuce',    quantity: 4,   unit: 'leaves', cost: 0.60, category: 'Produce',   allergens: [] },
        { name: 'Water chestnuts',   quantity: 0.25, unit: 'cup',  cost: 0.50, category: 'Pantry',     allergens: [] },
        { name: 'Soy sauce',         quantity: 1,   unit: 'tbsp',  cost: 0.10, category: 'Pantry',     allergens: ['soy'] },
        { name: 'Sesame oil',        quantity: 1,   unit: 'tsp',   cost: 0.15, category: 'Pantry',     allergens: ['nuts'] },
        { name: 'Garlic',            quantity: 2,   unit: 'cloves', cost: 0.10, category: 'Produce',   allergens: [] },
        { name: 'Ginger',            quantity: 0.5, unit: 'tsp',   cost: 0.05, category: 'Produce',    allergens: [] },
        { name: 'Spring onions',     quantity: 2,   unit: 'whole', cost: 0.20, category: 'Produce',    allergens: [] },
        { name: 'Sesame seeds',      quantity: 1,   unit: 'tsp',   cost: 0.05, category: 'Pantry',     allergens: ['nuts'] },
        { name: 'Sriracha',          quantity: 1,   unit: 'tsp',   cost: 0.10, category: 'Pantry',     allergens: [] },
      ],
      steps: [
        'Mince garlic and grate ginger; slice spring onions',
        'Heat a wok or pan over high heat until smoking',
        'Add minced chicken and cook, breaking up lumps, until browned',
        'Add garlic and ginger; cook 1 minute more',
        'Stir in soy sauce, sesame oil, and water chestnuts',
        'Cook 2 more minutes; taste and adjust seasoning',
        'Spoon into lettuce cups; top with sesame seeds, spring onions, and sriracha',
      ],
    },

    {
      id: 'lu-006',
      name: 'Classic Tuna Melt',
      type: 'lunch',
      tags: ['omnivore'],
      cuisine: 'american',
      servings: 1,
      prepTime: 8,
      cookTime: 5,
      difficulty: 'easy',
      emoji: '🐟',
      description: 'Toasted sourdough with creamy tuna salad and melted cheddar — a diner favourite',
      costPerServing: 4.50,
      ingredients: [
        { name: 'Canned tuna',        quantity: 1,   unit: 'can',   cost: 1.50, category: 'Proteins',    allergens: ['shellfish'] },
        { name: 'Sourdough bread',    quantity: 2,   unit: 'slices', cost: 0.80, category: 'Bakery',     allergens: ['gluten'] },
        { name: 'Cheddar cheese',     quantity: 2,   unit: 'slices', cost: 0.60, category: 'Dairy & Eggs', allergens: ['dairy'] },
        { name: 'Mayonnaise',         quantity: 1,   unit: 'tbsp',  cost: 0.20, category: 'Pantry',      allergens: ['eggs'] },
        { name: 'Celery',             quantity: 1,   unit: 'stalk', cost: 0.20, category: 'Produce',     allergens: [] },
        { name: 'Red onion',          quantity: 2,   unit: 'tbsp',  cost: 0.10, category: 'Produce',     allergens: [] },
        { name: 'Dijon mustard',      quantity: 0.5, unit: 'tsp',   cost: 0.05, category: 'Pantry',      allergens: [] },
        { name: 'Lemon juice',        quantity: 1,   unit: 'tsp',   cost: 0.05, category: 'Produce',     allergens: [] },
        { name: 'Black pepper',       quantity: 1,   unit: 'pinch', cost: 0.01, category: 'Pantry',      allergens: [] },
      ],
      steps: [
        'Drain canned tuna thoroughly and flake into a bowl',
        'Finely chop celery and red onion',
        'Mix tuna with mayo, mustard, lemon juice, celery, onion, and pepper',
        'Toast sourdough slices under the grill until lightly golden',
        'Spread tuna mixture generously on one slice',
        'Top with cheddar slices and grill until cheese is bubbling',
        'Close the sandwich, cut diagonally, and serve hot',
      ],
    },

    {
      id: 'lu-007',
      name: 'Quinoa Power Bowl',
      type: 'lunch',
      tags: ['vegan', 'vegetarian'],
      cuisine: 'american',
      servings: 1,
      prepTime: 5,
      cookTime: 20,
      difficulty: 'easy',
      emoji: '🫙',
      description: 'High-protein quinoa bowl with roasted broccoli, edamame, avocado, and miso dressing',
      costPerServing: 4.80,
      ingredients: [
        { name: 'Quinoa',      quantity: 0.5, unit: 'cup',   cost: 0.70, category: 'Pantry',   allergens: [] },
        { name: 'Broccoli',    quantity: 1,   unit: 'cup',   cost: 0.60, category: 'Produce',  allergens: [] },
        { name: 'Edamame',     quantity: 0.5, unit: 'cup',   cost: 0.80, category: 'Frozen',   allergens: ['soy'] },
        { name: 'Avocado',     quantity: 0.5, unit: 'whole', cost: 0.75, category: 'Produce',  allergens: [] },
        { name: 'Miso paste',  quantity: 1,   unit: 'tbsp',  cost: 0.30, category: 'Pantry',   allergens: ['soy'] },
        { name: 'Rice vinegar',quantity: 1,   unit: 'tbsp',  cost: 0.10, category: 'Pantry',   allergens: [] },
        { name: 'Sesame oil',  quantity: 1,   unit: 'tsp',   cost: 0.15, category: 'Pantry',   allergens: ['nuts'] },
        { name: 'Sesame seeds',quantity: 1,   unit: 'tsp',   cost: 0.05, category: 'Pantry',   allergens: ['nuts'] },
        { name: 'Olive oil',   quantity: 1,   unit: 'tbsp',  cost: 0.15, category: 'Pantry',   allergens: [] },
        { name: 'Salt',        quantity: 1,   unit: 'pinch', cost: 0.01, category: 'Pantry',   allergens: [] },
      ],
      steps: [
        'Cook quinoa in 1 cup of salted water for 15 minutes; fluff and cool',
        'Chop broccoli into florets and toss with olive oil and salt',
        'Roast broccoli at 200 °C / 400 °F for 15–18 minutes until slightly charred',
        'Cook edamame in boiling water for 3 minutes; drain and cool',
        'Whisk miso, rice vinegar, sesame oil, and 1 tbsp water for dressing',
        'Assemble: quinoa base, then broccoli, edamame, and sliced avocado',
        'Drizzle miso dressing and sprinkle sesame seeds',
      ],
    },

    {
      id: 'lu-008',
      name: 'Smoky BBQ Chicken Wrap',
      type: 'lunch',
      tags: ['omnivore'],
      cuisine: 'american',
      servings: 1,
      prepTime: 10,
      cookTime: 12,
      difficulty: 'easy',
      emoji: '🌯',
      description: 'Tender BBQ grilled chicken, crunchy slaw, and creamy ranch in a warm flour tortilla',
      costPerServing: 5.20,
      ingredients: [
        { name: 'Chicken thigh',    quantity: 120, unit: 'g',     cost: 1.50, category: 'Proteins',    allergens: [] },
        { name: 'Flour tortilla',   quantity: 1,   unit: 'large', cost: 0.40, category: 'Bakery',      allergens: ['gluten'] },
        { name: 'BBQ sauce',        quantity: 2,   unit: 'tbsp',  cost: 0.30, category: 'Pantry',      allergens: [] },
        { name: 'Coleslaw mix',     quantity: 0.5, unit: 'cup',   cost: 0.60, category: 'Produce',     allergens: [] },
        { name: 'Ranch dressing',   quantity: 1,   unit: 'tbsp',  cost: 0.20, category: 'Pantry',      allergens: ['dairy', 'eggs'] },
        { name: 'Cheddar cheese',   quantity: 2,   unit: 'tbsp',  cost: 0.30, category: 'Dairy & Eggs', allergens: ['dairy'] },
        { name: 'Red onion',        quantity: 2,   unit: 'tbsp',  cost: 0.10, category: 'Produce',     allergens: [] },
        { name: 'Jalapeños',        quantity: 4,   unit: 'slices', cost: 0.10, category: 'Pantry',     allergens: [] },
        { name: 'Smoked paprika',   quantity: 0.5, unit: 'tsp',   cost: 0.05, category: 'Pantry',      allergens: [] },
      ],
      steps: [
        'Season chicken thigh with smoked paprika and salt',
        'Grill on a hot pan 5–6 minutes per side until charred and cooked',
        'Brush chicken with BBQ sauce in the last 1 minute of cooking',
        'Rest chicken 2 minutes, then slice into strips',
        'Warm the tortilla in the same pan for 30 seconds',
        'Spread ranch dressing on the tortilla',
        'Layer chicken, coleslaw, cheddar, red onion, and jalapeños',
        'Roll tightly, slice at an angle, and serve',
      ],
    },

    /* ========================================================
       DINNER MEALS
       ======================================================== */

    {
      id: 'di-001',
      name: 'Spaghetti Bolognese',
      type: 'dinner',
      tags: ['omnivore'],
      cuisine: 'italian',
      servings: 1,
      prepTime: 10,
      cookTime: 30,
      difficulty: 'medium',
      emoji: '🍝',
      description: 'Slow-simmered rich meat ragu with Italian herbs on al dente spaghetti',
      costPerServing: 5.80,
      ingredients: [
        { name: 'Spaghetti',        quantity: 100, unit: 'g',     cost: 0.40, category: 'Pantry',       allergens: ['gluten'] },
        { name: 'Beef mince',       quantity: 150, unit: 'g',     cost: 2.50, category: 'Proteins',     allergens: [] },
        { name: 'Canned tomatoes',  quantity: 0.5, unit: 'can',   cost: 0.50, category: 'Pantry',       allergens: [] },
        { name: 'Onion',            quantity: 0.5, unit: 'whole', cost: 0.20, category: 'Produce',      allergens: [] },
        { name: 'Garlic',           quantity: 3,   unit: 'cloves', cost: 0.15, category: 'Produce',    allergens: [] },
        { name: 'Carrot',           quantity: 0.5, unit: 'whole', cost: 0.15, category: 'Produce',     allergens: [] },
        { name: 'Celery',           quantity: 1,   unit: 'stalk', cost: 0.15, category: 'Produce',     allergens: [] },
        { name: 'Tomato paste',     quantity: 1,   unit: 'tbsp',  cost: 0.15, category: 'Pantry',      allergens: [] },
        { name: 'Red wine',         quantity: 0.25, unit: 'cup',  cost: 0.50, category: 'Pantry',      allergens: [] },
        { name: 'Parmesan',         quantity: 2,   unit: 'tbsp',  cost: 0.50, category: 'Dairy & Eggs', allergens: ['dairy'] },
        { name: 'Italian herbs',    quantity: 1,   unit: 'tsp',   cost: 0.05, category: 'Pantry',      allergens: [] },
        { name: 'Olive oil',        quantity: 1,   unit: 'tbsp',  cost: 0.15, category: 'Pantry',      allergens: [] },
      ],
      steps: [
        'Finely dice onion, carrot, and celery (soffritto base)',
        'Heat olive oil in a heavy pan; cook soffritto 8 minutes until soft',
        'Add minced garlic and cook 1 minute more',
        'Add beef mince and cook, breaking up, until browned',
        'Stir in tomato paste and cook 2 minutes',
        'Pour in red wine and cook until mostly evaporated',
        'Add canned tomatoes, Italian herbs, salt, and pepper',
        'Simmer on low heat for 20–25 minutes, stirring occasionally',
        'Cook spaghetti al dente per packet instructions',
        'Toss pasta with bolognese sauce; top with Parmesan',
      ],
    },

    {
      id: 'di-002',
      name: 'Butter Chicken with Basmati Rice',
      type: 'dinner',
      tags: ['omnivore'],
      cuisine: 'indian',
      servings: 1,
      prepTime: 15,
      cookTime: 30,
      difficulty: 'medium',
      emoji: '🍛',
      description: 'Tender chicken in a velvety tomato-cream sauce spiced with garam masala',
      costPerServing: 6.50,
      ingredients: [
        { name: 'Chicken thigh',    quantity: 180, unit: 'g',     cost: 2.20, category: 'Proteins',    allergens: [] },
        { name: 'Basmati rice',     quantity: 0.5, unit: 'cup',   cost: 0.40, category: 'Pantry',      allergens: [] },
        { name: 'Canned tomatoes',  quantity: 0.5, unit: 'can',   cost: 0.50, category: 'Pantry',      allergens: [] },
        { name: 'Heavy cream',      quantity: 3,   unit: 'tbsp',  cost: 0.40, category: 'Dairy & Eggs', allergens: ['dairy'] },
        { name: 'Butter',           quantity: 2,   unit: 'tbsp',  cost: 0.30, category: 'Dairy & Eggs', allergens: ['dairy'] },
        { name: 'Onion',            quantity: 0.5, unit: 'whole', cost: 0.20, category: 'Produce',     allergens: [] },
        { name: 'Garlic',           quantity: 3,   unit: 'cloves', cost: 0.15, category: 'Produce',   allergens: [] },
        { name: 'Ginger',           quantity: 1,   unit: 'tsp',   cost: 0.10, category: 'Produce',    allergens: [] },
        { name: 'Garam masala',     quantity: 1,   unit: 'tsp',   cost: 0.10, category: 'Pantry',     allergens: [] },
        { name: 'Cumin',            quantity: 0.5, unit: 'tsp',   cost: 0.05, category: 'Pantry',     allergens: [] },
        { name: 'Yogurt',           quantity: 2,   unit: 'tbsp',  cost: 0.20, category: 'Dairy & Eggs', allergens: ['dairy'] },
        { name: 'Salt',             quantity: 1,   unit: 'pinch', cost: 0.01, category: 'Pantry',     allergens: [] },
      ],
      steps: [
        'Marinate chicken in yogurt, garam masala, cumin, and salt for 15 minutes',
        'Cook basmati rice per packet instructions; set aside',
        'Melt butter in a pan; cook onion until deep golden brown',
        'Add garlic and ginger paste; cook 2 minutes',
        'Blend canned tomatoes until smooth; add to pan',
        'Simmer tomato sauce 10 minutes until thick and deep red',
        'Add marinated chicken and cook 15 minutes until tender',
        'Stir in heavy cream and simmer 3 more minutes',
        'Serve over basmati rice; garnish with fresh coriander',
      ],
    },

    {
      id: 'di-003',
      name: 'Herb-Crusted Salmon with Asparagus',
      type: 'dinner',
      tags: ['omnivore', 'keto'],
      cuisine: 'american',
      servings: 1,
      prepTime: 10,
      cookTime: 15,
      difficulty: 'medium',
      emoji: '🐟',
      description: 'Oven-baked salmon fillet with lemon-herb crust alongside roasted asparagus',
      costPerServing: 9.00,
      ingredients: [
        { name: 'Salmon fillet',   quantity: 180, unit: 'g',     cost: 5.00, category: 'Proteins',  allergens: ['shellfish'] },
        { name: 'Asparagus',       quantity: 8,   unit: 'spears', cost: 1.20, category: 'Produce',  allergens: [] },
        { name: 'Dijon mustard',   quantity: 1,   unit: 'tbsp',  cost: 0.20, category: 'Pantry',   allergens: [] },
        { name: 'Garlic',          quantity: 2,   unit: 'cloves', cost: 0.10, category: 'Produce',  allergens: [] },
        { name: 'Fresh dill',      quantity: 1,   unit: 'tbsp',  cost: 0.30, category: 'Produce',  allergens: [] },
        { name: 'Fresh parsley',   quantity: 1,   unit: 'tbsp',  cost: 0.20, category: 'Produce',  allergens: [] },
        { name: 'Lemon',           quantity: 1,   unit: 'whole', cost: 0.30, category: 'Produce',  allergens: [] },
        { name: 'Olive oil',       quantity: 2,   unit: 'tbsp',  cost: 0.30, category: 'Pantry',   allergens: [] },
        { name: 'Parmesan',        quantity: 1,   unit: 'tbsp',  cost: 0.25, category: 'Dairy & Eggs', allergens: ['dairy'] },
        { name: 'Salt',            quantity: 1,   unit: 'pinch', cost: 0.01, category: 'Pantry',   allergens: [] },
      ],
      steps: [
        'Preheat oven to 200 °C / 400 °F; line a baking tray',
        'Mix mustard, minced garlic, dill, parsley, and Parmesan',
        'Pat salmon dry and season with salt; spread herb mixture on top',
        'Snap woody ends off asparagus; toss with olive oil, salt, and lemon zest',
        'Place salmon and asparagus on baking tray',
        'Bake 12–14 minutes until salmon flakes easily and asparagus is tender',
        'Finish with a squeeze of fresh lemon juice before serving',
      ],
    },

    {
      id: 'di-004',
      name: 'Creamy Pasta Primavera',
      type: 'dinner',
      tags: ['vegetarian'],
      cuisine: 'italian',
      servings: 1,
      prepTime: 10,
      cookTime: 20,
      difficulty: 'easy',
      emoji: '🍜',
      description: 'Al dente penne tossed with seasonal vegetables in a light parmesan cream sauce',
      costPerServing: 4.50,
      ingredients: [
        { name: 'Penne pasta',     quantity: 100, unit: 'g',     cost: 0.40, category: 'Pantry',       allergens: ['gluten'] },
        { name: 'Zucchini',        quantity: 0.5, unit: 'whole', cost: 0.40, category: 'Produce',      allergens: [] },
        { name: 'Bell pepper',     quantity: 0.5, unit: 'whole', cost: 0.40, category: 'Produce',      allergens: [] },
        { name: 'Cherry tomatoes', quantity: 8,   unit: 'whole', cost: 0.60, category: 'Produce',      allergens: [] },
        { name: 'Heavy cream',     quantity: 3,   unit: 'tbsp',  cost: 0.40, category: 'Dairy & Eggs', allergens: ['dairy'] },
        { name: 'Parmesan',        quantity: 3,   unit: 'tbsp',  cost: 0.75, category: 'Dairy & Eggs', allergens: ['dairy'] },
        { name: 'Garlic',          quantity: 2,   unit: 'cloves', cost: 0.10, category: 'Produce',     allergens: [] },
        { name: 'Fresh basil',     quantity: 5,   unit: 'leaves', cost: 0.20, category: 'Produce',     allergens: [] },
        { name: 'Butter',          quantity: 1,   unit: 'tbsp',  cost: 0.20, category: 'Dairy & Eggs', allergens: ['dairy'] },
        { name: 'Olive oil',       quantity: 1,   unit: 'tbsp',  cost: 0.15, category: 'Pantry',       allergens: [] },
      ],
      steps: [
        'Cook penne in salted boiling water until al dente; reserve ¼ cup pasta water',
        'Dice zucchini and bell pepper; halve cherry tomatoes',
        'Heat olive oil and butter; sauté garlic 1 minute',
        'Add zucchini and bell pepper; cook 5 minutes until tender',
        'Add cherry tomatoes and cook 2 minutes until they burst',
        'Pour in heavy cream and pasta water; simmer 2 minutes',
        'Toss drained pasta in the sauce with half the Parmesan',
        'Serve topped with remaining Parmesan and fresh basil',
      ],
    },

    {
      id: 'di-005',
      name: 'Street-Style Beef Tacos',
      type: 'dinner',
      tags: ['omnivore'],
      cuisine: 'mexican',
      servings: 1,
      prepTime: 10,
      cookTime: 15,
      difficulty: 'easy',
      emoji: '🌮',
      description: 'Soft corn tortillas loaded with spiced beef, fresh pico de gallo, and lime crema',
      costPerServing: 7.00,
      ingredients: [
        { name: 'Beef mince',        quantity: 150, unit: 'g',     cost: 2.50, category: 'Proteins',   allergens: [] },
        { name: 'Corn tortillas',    quantity: 3,   unit: 'whole', cost: 0.60, category: 'Bakery',     allergens: [] },
        { name: 'Tomato',            quantity: 1,   unit: 'whole', cost: 0.30, category: 'Produce',    allergens: [] },
        { name: 'Red onion',         quantity: 0.25, unit: 'whole', cost: 0.15, category: 'Produce',   allergens: [] },
        { name: 'Coriander/Cilantro',quantity: 2,  unit: 'tbsp',  cost: 0.15, category: 'Produce',    allergens: [] },
        { name: 'Lime',              quantity: 1,   unit: 'whole', cost: 0.25, category: 'Produce',    allergens: [] },
        { name: 'Sour cream',        quantity: 2,   unit: 'tbsp',  cost: 0.30, category: 'Dairy & Eggs', allergens: ['dairy'] },
        { name: 'Taco seasoning',    quantity: 1,   unit: 'tbsp',  cost: 0.30, category: 'Pantry',     allergens: [] },
        { name: 'Cheddar cheese',    quantity: 2,   unit: 'tbsp',  cost: 0.30, category: 'Dairy & Eggs', allergens: ['dairy'] },
        { name: 'Avocado',           quantity: 0.5, unit: 'whole', cost: 0.75, category: 'Produce',    allergens: [] },
        { name: 'Olive oil',         quantity: 1,   unit: 'tsp',   cost: 0.10, category: 'Pantry',     allergens: [] },
      ],
      steps: [
        'Finely dice tomato, red onion, and coriander for pico de gallo',
        'Mix pico with lime juice and a pinch of salt; set aside',
        'Brown beef mince in olive oil over high heat, 5 minutes',
        'Add taco seasoning and 3 tbsp water; cook 2 minutes until absorbed',
        'Warm corn tortillas directly over a gas flame or dry pan',
        'Mix sour cream with lime zest to make lime crema',
        'Build tacos: beef, pico de gallo, avocado slices, crema, and cheese',
      ],
    },

    {
      id: 'di-006',
      name: 'Thai Tofu Green Curry',
      type: 'dinner',
      tags: ['vegan', 'vegetarian'],
      cuisine: 'asian',
      servings: 1,
      prepTime: 10,
      cookTime: 20,
      difficulty: 'medium',
      emoji: '🍲',
      description: 'Creamy coconut green curry with crispy tofu, Thai basil, and jasmine rice',
      costPerServing: 5.20,
      ingredients: [
        { name: 'Firm tofu',          quantity: 150, unit: 'g',     cost: 1.00, category: 'Proteins',   allergens: ['soy'] },
        { name: 'Jasmine rice',       quantity: 0.5, unit: 'cup',   cost: 0.30, category: 'Pantry',     allergens: [] },
        { name: 'Coconut milk',       quantity: 0.75, unit: 'cup',  cost: 0.90, category: 'Dairy-Free', allergens: [] },
        { name: 'Green curry paste',  quantity: 1.5, unit: 'tbsp',  cost: 0.50, category: 'Pantry',     allergens: [] },
        { name: 'Zucchini',           quantity: 0.5, unit: 'whole', cost: 0.40, category: 'Produce',    allergens: [] },
        { name: 'Bell pepper',        quantity: 0.5, unit: 'whole', cost: 0.40, category: 'Produce',    allergens: [] },
        { name: 'Thai basil',         quantity: 0.25, unit: 'cup',  cost: 0.30, category: 'Produce',    allergens: [] },
        { name: 'Soy sauce',          quantity: 1,   unit: 'tbsp',  cost: 0.10, category: 'Pantry',     allergens: ['soy'] },
        { name: 'Coconut oil',        quantity: 1,   unit: 'tbsp',  cost: 0.20, category: 'Pantry',     allergens: [] },
        { name: 'Lime',               quantity: 0.5, unit: 'whole', cost: 0.15, category: 'Produce',    allergens: [] },
        { name: 'Vegetable broth',    quantity: 0.5, unit: 'cup',   cost: 0.15, category: 'Pantry',     allergens: [] },
      ],
      steps: [
        'Press tofu dry and cube into 2 cm pieces',
        'Cook jasmine rice per packet instructions; set aside',
        'Pan-fry tofu in coconut oil until golden on all sides; set aside',
        'In the same pan, fry green curry paste for 1 minute until fragrant',
        'Pour in coconut milk and vegetable broth; bring to a simmer',
        'Add sliced zucchini and bell pepper; cook 5 minutes',
        'Return tofu to the pan; add soy sauce and lime juice',
        'Stir in Thai basil and serve over jasmine rice',
      ],
    },

    {
      id: 'di-007',
      name: 'Garlic Butter Steak with Roasted Veg',
      type: 'dinner',
      tags: ['keto', 'omnivore'],
      cuisine: 'american',
      servings: 1,
      prepTime: 5,
      cookTime: 20,
      difficulty: 'medium',
      emoji: '🥩',
      description: 'Pan-seared ribeye finished with garlic herb butter, with crispy roasted vegetables',
      costPerServing: 12.00,
      ingredients: [
        { name: 'Ribeye steak',       quantity: 220, unit: 'g',      cost: 8.00, category: 'Proteins',    allergens: [] },
        { name: 'Butter',             quantity: 2,   unit: 'tbsp',   cost: 0.30, category: 'Dairy & Eggs', allergens: ['dairy'] },
        { name: 'Garlic',             quantity: 3,   unit: 'cloves', cost: 0.15, category: 'Produce',     allergens: [] },
        { name: 'Fresh rosemary',     quantity: 2,   unit: 'sprigs', cost: 0.25, category: 'Produce',     allergens: [] },
        { name: 'Thyme',              quantity: 2,   unit: 'sprigs', cost: 0.20, category: 'Produce',     allergens: [] },
        { name: 'Broccoli',           quantity: 1,   unit: 'cup',    cost: 0.60, category: 'Produce',     allergens: [] },
        { name: 'Cherry tomatoes',    quantity: 6,   unit: 'whole',  cost: 0.40, category: 'Produce',     allergens: [] },
        { name: 'Olive oil',          quantity: 1,   unit: 'tbsp',   cost: 0.15, category: 'Pantry',      allergens: [] },
        { name: 'Salt',               quantity: 1,   unit: 'tsp',    cost: 0.01, category: 'Pantry',      allergens: [] },
        { name: 'Black pepper',       quantity: 1,   unit: 'tsp',    cost: 0.05, category: 'Pantry',      allergens: [] },
        { name: 'Lemon',              quantity: 0.5, unit: 'whole',  cost: 0.15, category: 'Produce',     allergens: [] },
      ],
      steps: [
        'Bring steak to room temperature; season generously with salt and pepper',
        'Toss broccoli and tomatoes with olive oil; roast at 200 °C / 400 °F for 18 min',
        'Heat a cast-iron pan until smoking; sear steak 3 min per side',
        'Add butter, garlic, rosemary, and thyme to pan',
        'Baste steak repeatedly with melted garlic butter for 1–2 minutes',
        'Rest steak on a board for 5 minutes before slicing',
        'Serve steak sliced over roasted vegetables with lemon wedge',
      ],
    },

    {
      id: 'di-008',
      name: 'Sesame Noodle Stir Fry',
      type: 'dinner',
      tags: ['vegan', 'vegetarian'],
      cuisine: 'asian',
      servings: 1,
      prepTime: 10,
      cookTime: 10,
      difficulty: 'easy',
      emoji: '🍜',
      description: 'Silky rice noodles tossed with colourful vegetables in a rich sesame-soy sauce',
      costPerServing: 3.80,
      ingredients: [
        { name: 'Rice noodles',     quantity: 100, unit: 'g',     cost: 0.60, category: 'Pantry',   allergens: [] },
        { name: 'Broccoli',         quantity: 0.5, unit: 'cup',   cost: 0.30, category: 'Produce',  allergens: [] },
        { name: 'Carrot',           quantity: 1,   unit: 'whole', cost: 0.30, category: 'Produce',  allergens: [] },
        { name: 'Snap peas',        quantity: 0.5, unit: 'cup',   cost: 0.50, category: 'Produce',  allergens: [] },
        { name: 'Red bell pepper',  quantity: 0.5, unit: 'whole', cost: 0.40, category: 'Produce',  allergens: [] },
        { name: 'Soy sauce',        quantity: 2,   unit: 'tbsp',  cost: 0.20, category: 'Pantry',   allergens: ['soy'] },
        { name: 'Sesame oil',       quantity: 1,   unit: 'tbsp',  cost: 0.20, category: 'Pantry',   allergens: ['nuts'] },
        { name: 'Sesame seeds',     quantity: 1,   unit: 'tbsp',  cost: 0.10, category: 'Pantry',   allergens: ['nuts'] },
        { name: 'Garlic',           quantity: 2,   unit: 'cloves', cost: 0.10, category: 'Produce', allergens: [] },
        { name: 'Ginger',           quantity: 0.5, unit: 'tsp',   cost: 0.05, category: 'Produce',  allergens: [] },
        { name: 'Rice vinegar',     quantity: 1,   unit: 'tbsp',  cost: 0.10, category: 'Pantry',   allergens: [] },
        { name: 'Sriracha',         quantity: 1,   unit: 'tsp',   cost: 0.10, category: 'Pantry',   allergens: [] },
      ],
      steps: [
        'Soak rice noodles in hot water for 8 minutes; drain and set aside',
        'Julienne carrot, slice bell pepper, and cut broccoli into florets',
        'Whisk soy sauce, sesame oil, rice vinegar, and sriracha for sauce',
        'Heat a wok over maximum heat; add a splash of oil',
        'Stir fry all vegetables at high heat for 3–4 minutes',
        'Add minced garlic and ginger; toss 30 seconds',
        'Add noodles and sauce; toss everything together 2 minutes',
        'Serve topped with sesame seeds and extra sriracha',
      ],
    },

  ]
};
